# Example Kustomization configuration for DevOps workflows
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels applied to all resources
commonLabels:
  managed-by: kustomize
  environment: dev

# Common annotations
commonAnnotations:
  version: "1.0"

# List of resource files to include
resources:
  - deployments/
  - services/
  - configmaps/

# Patches for environment-specific modifications
patches:
  - target:
      kind: Deployment
      name: ".*"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENVIRONMENT
          value: development

# ConfigMap generator
configMapGenerator:
  - name: app-config
    literals:
      - environment=dev
      - log_level=debug

# Secret generator (for development only)
secretGenerator:
  - name: app-secrets
    literals:
      - api_key=dev-key-placeholder

# Image transformations
images:
  - name: app
    newName: myregistry/app
    newTag: latest

# Namespace to apply resources
namespace: default